# Generated by Django 4.0 on 2021-12-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='image',
        ),
    ]
